const{Pool}=require('pg'),express=require('express');
const a=express();a.use(express.json());
const p=new Pool({connectionString:'postgresql://persona_lab:persona_pass_2026@localhost:5432/persona_lab'});
const Q=[{i:1,d:'O',t:'I have a vivid imagination'},{i:2,d:'O',t:'I have original ideas'},{i:3,d:'O',t:'I value artistic experiences'},{i:4,d:'O',t:'I enjoy exploring new ideas'},{i:5,d:'O',t:'I am curious'},{i:6,d:'C',t:'I am always prepared'},{i:7,d:'C',t:'I pay attention to details'},{i:8,d:'C',t:'I follow through'},{i:9,d:'C',t:'I like structure'},{i:10,d:'C',t:'I set goals'},{i:11,d:'E',t:'I am talkative'},{i:12,d:'E',t:'I feel energized'},{i:13,d:'E',t:'I enjoy gatherings'},{i:14,d:'E',t:'I start conversations'},{i:15,d:'E',t:'I am outgoing'},{i:16,d:'A',t:'I trust others'},{i:17,d:'A',t:'I am considerate'},{i:18,d:'A',t:'I help others'},{i:19,d:'A',t:'I believe best'},{i:20,d:'A',t:'I get along'},{i:21,d:'N',t:'I feel anxious',iv:1},{i:22,d:'N',t:'I worry',iv:1},{i:23,d:'N',t:'I am unstable',iv:1},{i:24,d:'N',t:'I feel overwhelmed',iv:1},{i:25,d:'N',t:'I get nervous',iv:1}];
const O=['Strongly Agree','Agree','Neutral','Disagree','Strongly Disagree'];const S=[4,3,2,1,0];
a.get('/health',(_,r)=>r.json({ok:1}));
a.post('/sessions',async(i,r)=>{const s='s'+Date.now().toString(36),b=i.body||{};await p.query(`INSERT INTO sessions(id,user_id)VAL($1,$2)`,[s,b.userId]);r.json({sid:s})});
a.get('/sessions/:id/next',async(i,r)=>{const s=(await p.query(`SELECT*FROM sessions WHERE id=$1`,[i.params.id])).rows[0];if(!s)return r.json({q:{i:Q[0].i,d:Q[0].d,t:Q[0].t},p:{c:1,t:25}});if(s.state==='done')return r.json({done:true,res:C(s.answers)});const cu=(s.current_question||0)+1;r.json({q:{i:Q[cu-1].i,d:Q[cu-1].d,t:Q[cu-1].t,opts:O},p:{c:cu,t:25}})});
a.post('/sessions/:id/answer',async(i,r)=>{const s=(await p.query(`SELECT*FROM sessions WHERE id=$1`,[i.params.id])).rows[0];if(!s)return r.status(404).json({e:'nf'});const b=r.body||{},opt=b.optionId,qid=b.questionId;const cu=(s.current_question||0)+1;const q=Q[cu-1];const si=O.indexOf(opt);let sc=S[si]||2;if(q.iv)sc=4-sc;const an=(s.answers?s.answers:[],q.i);an.push({d:q.d,s:sc});await p.query(`UPDATE sessions SET current_question=$1,answers=$2 WHERE id=$3`,[cu,JSON.stringify(an),i.params.id]);if(cu>=25){await p.query(`UPDATE sessions SET state='done' WHERE id=$1`,[i.params.id]);return r.json({done:true,res:C(an)})}r.json({q:{i:Q[cu].i,d:Q[cu].d,t:Q[cu].t,opts:O},p:{c:cu+1,t:25}})});
function C(an){const sc={O:0,C:0,E:0,A:0,N:0},cn={O:0,C:0,E:0,A:0,N:0};(an||[]).forEach(a=>{if(a.d&&sc[a.d]!=null){sc[a.d]+=a.s;cn[a.d]++}});const pt={};for(let k in cn)pt[k]=Math.round((sc[k]/cn[k])/4*100);let mt='';mt+=pt.E>=50?'E':'I';mt+=pt.O>=50?'N':'S';mt+=pt.C>=50?'J':'P';mt+=pt.A>=50?'F':'T';return{mbti:mt,scores:pt}}
a.listen(3002,()=>console.log('[OK]v2.4'))();
